//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Interfaces
{
    [Serializable]
    public class HullDataMsg : Message
    {
        public const string k_RosMessageName = "interfaces/HullData";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.TemperatureMsg temperature;
        public Sensor.FluidPressureMsg pressure;
        public Sensor.RelativeHumidityMsg humidity;

        public HullDataMsg()
        {
            this.temperature = new Sensor.TemperatureMsg();
            this.pressure = new Sensor.FluidPressureMsg();
            this.humidity = new Sensor.RelativeHumidityMsg();
        }

        public HullDataMsg(Sensor.TemperatureMsg temperature, Sensor.FluidPressureMsg pressure, Sensor.RelativeHumidityMsg humidity)
        {
            this.temperature = temperature;
            this.pressure = pressure;
            this.humidity = humidity;
        }

        public static HullDataMsg Deserialize(MessageDeserializer deserializer) => new HullDataMsg(deserializer);

        private HullDataMsg(MessageDeserializer deserializer)
        {
            this.temperature = Sensor.TemperatureMsg.Deserialize(deserializer);
            this.pressure = Sensor.FluidPressureMsg.Deserialize(deserializer);
            this.humidity = Sensor.RelativeHumidityMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.temperature);
            serializer.Write(this.pressure);
            serializer.Write(this.humidity);
        }

        public override string ToString()
        {
            return "HullDataMsg: " +
            "\ntemperature: " + temperature.ToString() +
            "\npressure: " + pressure.ToString() +
            "\nhumidity: " + humidity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
