//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Interfaces
{
    [Serializable]
    public class MotorMsg : Message
    {
        public const string k_RosMessageName = "interfaces/Motor";
        public override string RosMessageName => k_RosMessageName;

        public short esc;
        public short direction;

        public MotorMsg()
        {
            this.esc = 0;
            this.direction = 0;
        }

        public MotorMsg(short esc, short direction)
        {
            this.esc = esc;
            this.direction = direction;
        }

        public static MotorMsg Deserialize(MessageDeserializer deserializer) => new MotorMsg(deserializer);

        private MotorMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.esc);
            deserializer.Read(out this.direction);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.esc);
            serializer.Write(this.direction);
        }

        public override string ToString()
        {
            return "MotorMsg: " +
            "\nesc: " + esc.ToString() +
            "\ndirection: " + direction.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
