//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Interfaces
{
    [Serializable]
    public class ControlDataMsg : Message
    {
        public const string k_RosMessageName = "interfaces/ControlData";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.ImuMsg imu_data;
        public double depth;

        public ControlDataMsg()
        {
            this.imu_data = new Sensor.ImuMsg();
            this.depth = 0.0;
        }

        public ControlDataMsg(Sensor.ImuMsg imu_data, double depth)
        {
            this.imu_data = imu_data;
            this.depth = depth;
        }

        public static ControlDataMsg Deserialize(MessageDeserializer deserializer) => new ControlDataMsg(deserializer);

        private ControlDataMsg(MessageDeserializer deserializer)
        {
            this.imu_data = Sensor.ImuMsg.Deserialize(deserializer);
            deserializer.Read(out this.depth);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.imu_data);
            serializer.Write(this.depth);
        }

        public override string ToString()
        {
            return "ControlDataMsg: " +
            "\nimu_data: " + imu_data.ToString() +
            "\ndepth: " + depth.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
