//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Interfaces
{
    [Serializable]
    public class DepthGoalMsg : Message
    {
        public const string k_RosMessageName = "interfaces/DepthGoal";
        public override string RosMessageName => k_RosMessageName;

        public double depth;

        public DepthGoalMsg()
        {
            this.depth = 0.0;
        }

        public DepthGoalMsg(double depth)
        {
            this.depth = depth;
        }

        public static DepthGoalMsg Deserialize(MessageDeserializer deserializer) => new DepthGoalMsg(deserializer);

        private DepthGoalMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.depth);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.depth);
        }

        public override string ToString()
        {
            return "DepthGoalMsg: " +
            "\ndepth: " + depth.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
