//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Interfaces
{
    [Serializable]
    public class HeadingGoalMsg : Message
    {
        public const string k_RosMessageName = "interfaces/HeadingGoal";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.QuaternionMsg orientation;
        public double max_power;

        public HeadingGoalMsg()
        {
            this.orientation = new Geometry.QuaternionMsg();
            this.max_power = 0.0;
        }

        public HeadingGoalMsg(Geometry.QuaternionMsg orientation, double max_power)
        {
            this.orientation = orientation;
            this.max_power = max_power;
        }

        public static HeadingGoalMsg Deserialize(MessageDeserializer deserializer) => new HeadingGoalMsg(deserializer);

        private HeadingGoalMsg(MessageDeserializer deserializer)
        {
            this.orientation = Geometry.QuaternionMsg.Deserialize(deserializer);
            deserializer.Read(out this.max_power);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.orientation);
            serializer.Write(this.max_power);
        }

        public override string ToString()
        {
            return "HeadingGoalMsg: " +
            "\norientation: " + orientation.ToString() +
            "\nmax_power: " + max_power.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
