//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Interfaces
{
    [Serializable]
    public class MappingsMsg : Message
    {
        public const string k_RosMessageName = "interfaces/Mappings";
        public override string RosMessageName => k_RosMessageName;

        public MotorMsg motor1;
        public MotorMsg motor2;
        public MotorMsg motor3;
        public MotorMsg motor4;
        public MotorMsg motor5;
        public MotorMsg motor6;
        public MotorMsg motor7;
        public MotorMsg motor8;

        public MappingsMsg()
        {
            this.motor1 = new MotorMsg();
            this.motor2 = new MotorMsg();
            this.motor3 = new MotorMsg();
            this.motor4 = new MotorMsg();
            this.motor5 = new MotorMsg();
            this.motor6 = new MotorMsg();
            this.motor7 = new MotorMsg();
            this.motor8 = new MotorMsg();
        }

        public MappingsMsg(MotorMsg motor1, MotorMsg motor2, MotorMsg motor3, MotorMsg motor4, MotorMsg motor5, MotorMsg motor6, MotorMsg motor7, MotorMsg motor8)
        {
            this.motor1 = motor1;
            this.motor2 = motor2;
            this.motor3 = motor3;
            this.motor4 = motor4;
            this.motor5 = motor5;
            this.motor6 = motor6;
            this.motor7 = motor7;
            this.motor8 = motor8;
        }

        public static MappingsMsg Deserialize(MessageDeserializer deserializer) => new MappingsMsg(deserializer);

        private MappingsMsg(MessageDeserializer deserializer)
        {
            this.motor1 = MotorMsg.Deserialize(deserializer);
            this.motor2 = MotorMsg.Deserialize(deserializer);
            this.motor3 = MotorMsg.Deserialize(deserializer);
            this.motor4 = MotorMsg.Deserialize(deserializer);
            this.motor5 = MotorMsg.Deserialize(deserializer);
            this.motor6 = MotorMsg.Deserialize(deserializer);
            this.motor7 = MotorMsg.Deserialize(deserializer);
            this.motor8 = MotorMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.motor1);
            serializer.Write(this.motor2);
            serializer.Write(this.motor3);
            serializer.Write(this.motor4);
            serializer.Write(this.motor5);
            serializer.Write(this.motor6);
            serializer.Write(this.motor7);
            serializer.Write(this.motor8);
        }

        public override string ToString()
        {
            return "MappingsMsg: " +
            "\nmotor1: " + motor1.ToString() +
            "\nmotor2: " + motor2.ToString() +
            "\nmotor3: " + motor3.ToString() +
            "\nmotor4: " + motor4.ToString() +
            "\nmotor5: " + motor5.ToString() +
            "\nmotor6: " + motor6.ToString() +
            "\nmotor7: " + motor7.ToString() +
            "\nmotor8: " + motor8.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
