//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Interfaces
{
    [Serializable]
    public class MotorPowersMsg : Message
    {
        public const string k_RosMessageName = "interfaces/MotorPowers";
        public override string RosMessageName => k_RosMessageName;

        public double motor1;
        public double motor2;
        public double motor3;
        public double motor4;
        public double motor5;
        public double motor6;
        public double motor7;
        public double motor8;

        public MotorPowersMsg()
        {
            this.motor1 = 0.0;
            this.motor2 = 0.0;
            this.motor3 = 0.0;
            this.motor4 = 0.0;
            this.motor5 = 0.0;
            this.motor6 = 0.0;
            this.motor7 = 0.0;
            this.motor8 = 0.0;
        }

        public MotorPowersMsg(double motor1, double motor2, double motor3, double motor4, double motor5, double motor6, double motor7, double motor8)
        {
            this.motor1 = motor1;
            this.motor2 = motor2;
            this.motor3 = motor3;
            this.motor4 = motor4;
            this.motor5 = motor5;
            this.motor6 = motor6;
            this.motor7 = motor7;
            this.motor8 = motor8;
        }

        public static MotorPowersMsg Deserialize(MessageDeserializer deserializer) => new MotorPowersMsg(deserializer);

        private MotorPowersMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.motor1);
            deserializer.Read(out this.motor2);
            deserializer.Read(out this.motor3);
            deserializer.Read(out this.motor4);
            deserializer.Read(out this.motor5);
            deserializer.Read(out this.motor6);
            deserializer.Read(out this.motor7);
            deserializer.Read(out this.motor8);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.motor1);
            serializer.Write(this.motor2);
            serializer.Write(this.motor3);
            serializer.Write(this.motor4);
            serializer.Write(this.motor5);
            serializer.Write(this.motor6);
            serializer.Write(this.motor7);
            serializer.Write(this.motor8);
        }

        public override string ToString()
        {
            return "MotorPowersMsg: " +
            "\nmotor1: " + motor1.ToString() +
            "\nmotor2: " + motor2.ToString() +
            "\nmotor3: " + motor3.ToString() +
            "\nmotor4: " + motor4.ToString() +
            "\nmotor5: " + motor5.ToString() +
            "\nmotor6: " + motor6.ToString() +
            "\nmotor7: " + motor7.ToString() +
            "\nmotor8: " + motor8.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
