//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Interfaces
{
    [Serializable]
    public class UnityFrameMsg : Message
    {
        public const string k_RosMessageName = "interfaces/UnityFrame";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.ImageMsg Frame;

        public UnityFrameMsg()
        {
            this.Frame = new Sensor.ImageMsg();
        }

        public UnityFrameMsg(Sensor.ImageMsg Frame)
        {
            this.Frame = Frame;
        }

        public static UnityFrameMsg Deserialize(MessageDeserializer deserializer) => new UnityFrameMsg(deserializer);

        private UnityFrameMsg(MessageDeserializer deserializer)
        {
            this.Frame = Sensor.ImageMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.Frame);
        }

        public override string ToString()
        {
            return "UnityFrameMsg: " +
            "\nFrame: " + Frame.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
