//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Interfaces
{
    [Serializable]
    public class Yolov8DetectionMsg : Message
    {
        public const string k_RosMessageName = "interfaces/Yolov8Detection";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public long tracking_id;
        public double confidence;
        public Geometry.PointMsg center;
        public Geometry.PointMsg dimensions;

        public Yolov8DetectionMsg()
        {
            this.name = "";
            this.tracking_id = 0;
            this.confidence = 0.0;
            this.center = new Geometry.PointMsg();
            this.dimensions = new Geometry.PointMsg();
        }

        public Yolov8DetectionMsg(string name, long tracking_id, double confidence, Geometry.PointMsg center, Geometry.PointMsg dimensions)
        {
            this.name = name;
            this.tracking_id = tracking_id;
            this.confidence = confidence;
            this.center = center;
            this.dimensions = dimensions;
        }

        public static Yolov8DetectionMsg Deserialize(MessageDeserializer deserializer) => new Yolov8DetectionMsg(deserializer);

        private Yolov8DetectionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.tracking_id);
            deserializer.Read(out this.confidence);
            this.center = Geometry.PointMsg.Deserialize(deserializer);
            this.dimensions = Geometry.PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.tracking_id);
            serializer.Write(this.confidence);
            serializer.Write(this.center);
            serializer.Write(this.dimensions);
        }

        public override string ToString()
        {
            return "Yolov8DetectionMsg: " +
            "\nname: " + name.ToString() +
            "\ntracking_id: " + tracking_id.ToString() +
            "\nconfidence: " + confidence.ToString() +
            "\ncenter: " + center.ToString() +
            "\ndimensions: " + dimensions.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
